### ISSUE TITLE
Test HDFS

### ISSUE THREAD

**Issue by brianblessouBD** [brianblessouBD/SEBC#9]

**Comment by mfernest** [comment]
Hi Brian -

Note in your command: 

```
time hadoop jar /opt/cloudera/parcels/CDH-5.13.2-1.cdh5.13.2.p0.3/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar teragen -Dmapreduce.map.memory.mb=768 -Dmapreduce.reduce.memory.mb=768 -Dmapred.reduce.tasks=16 -Dmapred.map.tasks=16 -Ddfs.blocksize=64000000 65536 /user/hilary/tgen
```
You've generated 65,536 records instead of the 65,536,000 required. You can see in the following commands that you've generated 16 output files each containing 409600. And, of course, the job ran super fast. 

Also notice that teragen jobs only run mappers. The call for 16 reducers is ignored.
